
CREATE TABLE OVT_PAIS (ID_PAIS NUMBER PRIMARY KEY,
                NOME_PAIS VARCHAR2(30)NOT NULL);
                
CREATE TABLE OVT_ESTADO (ID_ESTADO NUMBER PRIMARY KEY,
                NOME_ESTADO VARCHAR2(30) NOT NULL,
                ID_PAIS NUMBER);

ALTER TABLE OVT_ESTADO ADD CONSTRAINT OV_FK_ESTADO FOREIGN KEY
(ID_ESTADO) REFERENCES OVT_PAIS (ID_PAIS);

select * from OVT_PAIS;
select * from OVT_ESTADO;

insert into OVT_ESTADO VALUES(1, 'São Paulo', 1);

insert into OVT_PAIS values (1, 'BRASIL');

